### ISSUE TITLE
Find out maximum supported integer for encoding/decoding

### ISSUE THREAD

**Issue by mhotchen** [craftwork/id-obfuscator#5]
Perform some research to find out what the maximum number is for encoding and decoding. Document these limits and create a new issue to increase the limit.

**Comment by fra-c** [comment]
```php
$obfuscator = new IdObfuscator('');

for ($id = PHP_INT_MAX; $id > 0; $id--) {
    
    $encoded = $obfuscator->encode($id);
    
    try {
        $decoded = $obfuscator->decode($encoded);
    } catch(TypeError $exception) {
        continue;
    }
    
    if ($decoded === $id) {
        echo 'Max number is: ' . $id;
        break;
    }
}
```

I've run this script to calculate the biggest number and found out that it's affected by the character set.

The salt seems to be irrelevant.

**Comment by mhotchen** [comment]
So the encode works fine, but decoding again is where the problem is?

**Comment by mhotchen** [comment]
Also what does the exception/error actually say?

**Comment by fra-c** [comment]
Encode have problems too when diving the number by the character set length..

I think we need a way to provide optional support for big numbers libraries.

I say optional because on my machine I get 9223372036854775232 as max number and I think it would be big enough in most cases.

**Comment by fra-c** [comment]
It's a TypeError, decode() returns a float instead of an integer. Something like 1.4411518807586E+17

**Comment by mhotchen** [comment]
You could probably get away with casting the decode value to an int. Yeah maybe we could use a strategy pattern to use bcmath or something. I think for v1 though 9223372036854775232 is plenty
