### ISSUE TITLE
Add more information to composer.json

### ISSUE THREAD

**Issue by amneale** [craftwork/id-obfuscator#9]
I just noticed our license isn't being picked up by packagist, as it relies on it being in the composer.json file. We should also add some other information that is usually generated when running composer --init:

- description
- author
- type
- homepage
- license

**Comment by mhotchen** [comment]
license: MIT
description: A base converter to obfuscate database IDs in front end applications. 
author: https://github.com/symfony/symfony/blob/master/composer.json#L8 style with Francesco, then Craftwork (home page can just be github.com/craftwork)
type: library
homepage: github.com/craftwork
